# © 2024 Carl Åstholm
# SPDX-License-Identifier: MIT

# REUSE <https://reuse.software/>
version = 1

# ALSA_LIB

[[annotations]]
path = "include/alsa/**"
SPDX-FileCopyrightText = [
    "1998-2001 Jaroslav Kysela <perex@perex.cz>",
    "1998-2001 Abramo Bagnara <abramo@alsa-project.org>",
    "1998-2001 Takashi Iwai <tiwai@suse.de>"
] # From file header comments
SPDX-License-Identifier = "LGPL-2.1-or-later"

[[annotations]]
path = [
    "include/alsa/pcm_old.h",
    "include/alsa/ump.h",
    "include/alsa/version.h",
]
SPDX-FileCopyrightText = "NONE" # No copyright notice
SPDX-License-Identifier = "LGPL-2.1-or-later"

[[annotations]]
path = [
    "include/alsa/ump.h",
    "include/alsa/ump_msg.h",
]
precedence = "override" # Override deprecated 'LGPL-2.1+' identifier
SPDX-FileCopyrightText = "NONE" # No copyright notice
SPDX-License-Identifier = "LGPL-2.1-or-later"

# DRM

[[annotations]]
path = [
    "include/drm.h",
    "include/drm_mode.h",
    "include/xf86drm.h",
    "include/xf86drmMode.h",
]
SPDX-License-Identifier = "MIT"

# FRIBIDI

[[annotations]]
path = "include/fribidi*.h"
SPDX-License-Identifier = "LGPL-2.1-or-later"

[[annotations]]
path = [
    "include/fribidi-begindecls.h",
    "include/fribidi-config.h",
    "include/fribidi-enddecls.h",
    "include/fribidi-unicode-version.h",
]
SPDX-FileCopyrightText = "NONE" # No copyright notice
SPDX-License-Identifier = "LGPL-2.1-or-later"

# GLIB

[[annotations]]
path = [
    "include/aarch64-linux-gnu/glibconfig.h",
    "include/aarch64-linux-musl/glibconfig.h",
    "include/gio/gio-visibility.h",
    "include/glib/deprecated/gallocator.h",
    "include/glib/glib-visibility.h",
    "include/gmodule/gmodule-visibility.h",
    "include/gobject/glib-enumtypes.h",
    "include/gobject/gmarshal.h",
    "include/gobject/gobject-visibility.h",
    "include/x86_64-linux-gnu/glibconfig.h",
    "include/x86_64-linux-musl/glibconfig.h",
]
SPDX-FileCopyrightText = "NONE" # No copyright notice
SPDX-License-Identifier = "LGPL-2.1-or-later"

[[annotations]]
path = "include/glib/gsequence.h"
precedence = "override" # Copyright notice present in file but spans multiple lines
SPDX-FileCopyrightText = "Copyright (C) 2002, 2003, 2004, 2005, 2006, 2007 Soeren Sandmann (sandmann@daimi.au.dk)"
SPDX-License-Identifier = "LGPL-2.1-or-later"

[[annotations]]
path = "include/glib/guuid.h"
SPDX-License-Identifier = "LGPL-2.1-or-later"

# IBUS

[[annotations]]
path = "include/ibus*.h"
SPDX-License-Identifier = "LGPL-2.1-or-later"

[[annotations]]
path = "include/ibusenumtypes.h"
SPDX-FileCopyrightText = "NONE" # No copyright notice
SPDX-License-Identifier = "LGPL-2.1-or-later"

# JACK1

[[annotations]]
path = "include/jack/**"
SPDX-License-Identifier = "LGPL-2.1-or-later"

# LIBDECOR

[[annotations]]
path = "include/libdecor.h"
SPDX-License-Identifier = "MIT"

# LIBTHAI

[[annotations]]
path = "include/thai/**"
SPDX-License-Identifier = "LGPL-2.1-or-later"

# LIBURING

[[annotations]]
path = [
    "include/liburing/barrier.h",
    "include/liburing/compat.h",
    "include/liburing/io_uring_version.h",
    "include/liburing.h",
]
SPDX-FileCopyrightText = "Copyright 2020 Jens Axboe" # From license

[[annotations]]
path = "include/liburing/io_uring.h"
precedence = "override" # Override deprecated 'GPL-2.0' identifier
SPDX-FileCopyrightText = [
    "Copyright (C) 2019 Jens Axboe",
    "Copyright (C) 2019 Christoph Hellwig",
]
SPDX-License-Identifier = "(GPL-2.0-only WITH Linux-syscall-note) OR MIT"

[[annotations]]
path = "include/liburing/io_uring/query.h"
precedence = "override" # Override deprecated 'GPL-2.0' identifier
SPDX-FileCopyrightText = "Copyright 2020 Jens Axboe" # From license
SPDX-License-Identifier = "(GPL-2.0-only WITH Linux-syscall-note) OR MIT"

# LIBUSB

[[annotations]]
path = "include/libusb.h"
SPDX-License-Identifier = "LGPL-2.1-or-later"

# LIBX11

[[annotations]]
path = "include/X11/XKBlib.h"
SPDX-License-Identifier = "HPND"

[[annotations]]
path = [
    "include/X11/Xlib.h",
    "include/X11/Xlibint.h",
    "include/X11/cursorfont.h",
]
SPDX-License-Identifier = "MIT-open-group"

[[annotations]]
path = "include/X11/XlibConf.h"
SPDX-License-Identifier = "HPND-sell-variant"

[[annotations]]
path = [
    "include/X11/Xresource.h",
    "include/X11/Xutil.h",
]
SPDX-License-Identifier = "MIT-open-group AND HPND"

# LIBXCB

[[annotations]]
path = "include/xcb/xcb.h"
SPDX-License-Identifier = "X11"

# LIBXCURSOR

[[annotations]]
path = "include/X11/Xcursor/Xcursor.h"
SPDX-License-Identifier = "HPND-sell-variant"

# LIBXEXT

[[annotations]]
path = [
    "include/X11/extensions/XShm.h",
    "include/X11/extensions/Xext.h",
    "include/X11/extensions/shape.h",
]
SPDX-License-Identifier = "MIT-open-group"

[[annotations]]
path = "include/X11/extensions/Xdbe.h"
SPDX-License-Identifier = "X11"

[[annotations]]
path = "include/X11/extensions/Xge.h"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "include/X11/extensions/sync.h"
precedence = "override" # Copyright notice present in file but spans multiple lines
SPDX-FileCopyrightText = [
    "Copyright 1991, 1993, 1994, 1998  The Open Group",
    "Copyright 1991,1993 by Digital Equipment Corporation, Maynard, Massachusetts, and Olivetti Research Limited, Cambridge, England.",
]
SPDX-License-Identifier = "MIT-open-group AND HPND"

# LIBXFIXES

[[annotations]]
path = "include/X11/extensions/Xfixes.h"
SPDX-License-Identifier = "MIT AND HPND-sell-variant"

# LIBXI

[[annotations]]
path = "include/X11/extensions/XInput.h"
SPDX-License-Identifier = "MIT-open-group AND HPND"

[[annotations]]
path = "include/X11/extensions/XInput2.h"
SPDX-License-Identifier = "MIT"

# LIBXKBCOMMON

[[annotations]]
path = "include/xkbcommon/xkbcommon-keysyms.h"
SPDX-License-Identifier = "MIT-open-group AND HPND"

# LIBXRANDR

[[annotations]]
path = "include/X11/extensions/Xrandr.h"
SPDX-License-Identifier = "HPND-sell-variant"

# LIBXRENDER

[[annotations]]
path = "include/X11/extensions/Xrender.h"
SPDX-License-Identifier = "HPND-sell-variant"

# LIBXSCRNSAVER

[[annotations]]
path = "include/X11/extensions/scrnsaver.h"
SPDX-License-Identifier = "X11"

# LIBXTST

[[annotations]]
path = "include/X11/extensions/XTest.h"
SPDX-License-Identifier = "MIT-open-group"

# MESA

[[annotations]]
path = [
    "include/GL/**",
    "include/gbm.h",
]
SPDX-License-Identifier = "MIT"

# PULSEAUDIO

[[annotations]]
path = "include/pulse/**"
SPDX-License-Identifier = "LGPL-2.1-or-later"

# SDL

[[annotations]]
path = "src/*-protocol.*"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "src/pointer-gestures-unstable-v1-*"
SPDX-FileCopyrightText = [
    'Copyright © 2008-2013 Kristian Høgsberg',
    'Copyright © 2010-2013 Intel Corporation',
    'Copyright © 2013 Rafael Antognolli',
    'Copyright © 2013 Jasper St. Pierre',
    'Copyright © 2014 Jonas Ådahl',
    'Copyright © 2014 Jason Ekstrand',
    'Copyright © 2014-2015 Collabora, Ltd.',
    'Copyright © 2015 Red Hat Inc.',
] # From upstream repo
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "src/tablet-v2-client-protocol.h"
SPDX-FileCopyrightText = [
    "Copyright 2014 © Stephen \"Lyude\" Chandler Paul",
    "Copyright 2015-2016 © Red Hat, Inc.",
] # Copyright notices present in file but not picked up by reuse
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "src/text-input-unstable-v3-*"
SPDX-License-Identifier = "HPND-sell-variant"

# SNDIO

[[annotations]]
path = "include/sndio.h"
SPDX-License-Identifier = "ISC"

# SYSTEMD

[[annotations]]
path = "include/libudev.h"
SPDX-FileCopyrightText = "NONE" # No copyright notice

# WAYLAND

[[annotations]]
path = "include/wayland-*.h"
SPDX-License-Identifier = "MIT"

# XCBPROTO

[[annotations]]
path = "include/xcb/xproto.h"
SPDX-FileCopyrightText = "Copyright (C) 2001-2004 Bart Massey, Jamey Sharp, and Josh Triplett." # From XML protocol
SPDX-License-Identifier = "X11"

# XORGPROTO

[[annotations]]
path = [
    "include/X11/extensions/XI.h",
    "include/X11/extensions/xtestconst.h",
    "include/X11/X.h",
    "include/X11/Xmd.h",
    "include/X11/Xproto.h",
    "include/X11/Xprotostr.h",
    "include/X11/keysym.h",
    "include/X11/keysymdef.h",
]
SPDX-License-Identifier = "MIT-open-group AND HPND"

[[annotations]]
path = "include/X11/Xatom.h"
SPDX-FileCopyrightText = "NONE" # No copyright notice
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
    "include/X11/extensions/shapeconst.h",
    "include/X11/extensions/shm.h",
    "include/X11/Xdefs.h",
    "include/X11/Xfuncproto.h",
    "include/X11/Xfuncs.h",
    "include/X11/Xosdefs.h",
    "include/X11/Xthreads.h",
]
SPDX-License-Identifier = "MIT-open-group"

[[annotations]]
path = "include/X11/extensions/XI2.h"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
    "include/X11/extensions/XKB.h",
    "include/X11/extensions/XKBstr.h",
]
SPDX-License-Identifier = "HPND"

[[annotations]]
path = [
    "include/X11/extensions/dbe.h",
    "include/X11/extensions/saver.h",
]
SPDX-License-Identifier = "X11"

[[annotations]]
path = [
    "include/X11/extensions/randr.h",
    "include/X11/extensions/render.h",
]
SPDX-License-Identifier = "HPND-sell-variant"

[[annotations]]
path = [
    "include/X11/extensions/syncconst.h",
    "include/X11/extensions/syncproto.h",
]
precedence = "override" # Copyright notice present in file but spans multiple lines
SPDX-FileCopyrightText = [
    "Copyright 1991, 1993, 1994, 1998  The Open Group",
    "Copyright 1991,1993 by Digital Equipment Corporation, Maynard, Massachusetts, and Olivetti Research Limited, Cambridge, England.",
]
SPDX-License-Identifier = "MIT-open-group AND HPND"

[[annotations]]
path = "include/X11/extensions/xfixeswire.h"
SPDX-License-Identifier = "MIT AND HPND-sell-variant"
